director_uuid: DIRECTOR_UUID
name: NAME

meta:
  environment: shibboleth
  dns_root: microbosh
  security_groups:
    - shibboleth
  stemcell:
    name: STEMCELL
  az1: us-east-1b
  az2: us-east-1d

releases:
  - name: shibboleth
    version: latest

compilation:
  cloud_properties:
    availability_zone: (( grab meta.az1 ))

resource_pools:
- name: small_z1
  cloud_properties:
    elbs: [ELB_NAME]
    availability_zone: (( grab meta.az1 ))

- name: small_z2
  cloud_properties:
    elbs: [ELB_NAME]
    availability_zone: (( grab meta.az2 ))

jobs:
  - name: idp_z1
    instances: 2
  - name: idp_z2
    instances: 1

networks:
- name: shibboleth1
  subnets:
  - cloud_properties:
      subnet: SUBNET
      security_groups:
      - SECURITY_GROUP
    range: ADDRESS_RANGE
    gateway: GATEWAY_ADDRESS
    reserved:
    - RESERVED_ADDRESS
    dns:
    - DNS_ADDRESS

- name: shibboleth2
  subnets:
  - cloud_properties:
      subnet: SUBNET
      security_groups:
      - SECURITY_GROUP
    range: ADDRESS_RANGE
    gateway: GATEWAY_ADDRESS
    reserved:
    - RESERVED_ADDRESS
    dns:
    - DNS_ADDRESS

properties:
  root:
    title: ROOT_TITLE
    footer: ROOT_FOOTER
  idp:
    description: DESCRIPTION
    jaas:
      database:
        dbURL: DATABASE_URL
        dbUser: DATABASE_USER
        dbPassword: DATABASE_URL
    port: PORT_NUMBER
    title: IDP_PAGE_TITLE
    footer: IDP_PAGE_FOOTER
    logo:
      alt-text: IMAGE_TAG_ALT_TEXT
      src: BASE64_IMAGE_DATA_URI
    sslPrivateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MY PRIVATE KEY
      -----END RSA PRIVATE KEY-----
    sslCertificate: |
      -----BEGIN CERTIFICATE-----
      MY CERT
      -----END CERTIFICATE-----
    signing:
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MY PRIVATE SAML SIGNING KEY
        -----END RSA PRIVATE KEY-----
      cert: |
        -----BEGIN CERTIFICATE-----
        MY SAML SIGNING CERT
        -----END CERTIFICATE-----
    entityID: https://localhost.localdomain
    scope: localdomain
    passwords:
      sealer: CHANGEME
    metadata:
      providers:
      - id: testshib
        metadataURL: https://www.testshib.org/metadata/testshib-providers.xml
