---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: idp
  stemcell: default
  templates:
  - name: idp
    release: shibboleth
  azs: [z1, z2]
  vm_type: shibboleth
  vm_extensions: [shibboleth-lb]
  disk_type: shibboleth
  instances: 2
  networks:
  - name: shibboleth
