---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: idp_z1
    templates:
    - name: idp
      release: shibboleth
    - {name: newrelic-monitor, release: newrelic}
    - {name: nessus-agent, release: nessus-agent}
    - {name: harden, release: fisma}
    - {name: collectd, release: collectd}
    - {name: tripwire, release: tripwire}
    - {name: awslogs, release: awslogs}
    - {name: riemannc, release: riemannc}
    - {name: clamav, release: clamav}
    - {name: snort, release: snort}
    - {name: cron, release: cron}
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))

  - name: idp_z2
    templates:
    - name: idp
      release: shibboleth
    - {name: newrelic-monitor, release: newrelic}
    - {name: nessus-agent, release: nessus-agent}
    - {name: harden, release: fisma}
    - {name: collectd, release: collectd}
    - {name: tripwire, release: tripwire}
    - {name: awslogs, release: awslogs}
    - {name: riemannc, release: riemannc}
    - {name: clamav, release: clamav}
    - {name: snort, release: snort}
    - {name: cron, release: cron}
    instances: 0
    persistent_disk: 0
    resource_pool: small_z2
    networks: (( param "Please configure the networks for this job" ))

networks: (( param "Please configure the global network definitions for this deployment" ))
