---
meta:
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: idp_z1
    networks:
      - name: shibboleth1
    persistent_disk: (( grab meta.persistent_disk ))
  - name: idp_z2
    networks:
      - name: shibboleth2
    persistent_disk: (( grab meta.persistent_disk ))

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m3.medium
      elbs: (( param "Please configure the global ELB definition for this deployment" ))
  - name: small_z2
    cloud_properties:
      instance_type: m3.medium
      elbs: (( param "Please configure the global ELB definition for this deployment" ))

networks:
  - name: shibboleth1
    type: dynamic
  - name: shibboleth2
    type: dynamic