---
meta:
  dns_root: microbosh
  environment: (( merge ))
  security_groups:
  - shibboleth
  stemcell:
    name: (( merge ))
    version: latest

compilation:
  cloud_properties:
    name: random
  network: shibboleth1
  reuse_compilation_vms: true
  workers: 6

name: (( grab meta.environment ))
director_uuid: PLACEHOLDER-DIRECTOR-UUID

jobs:
- instances: 1
  name: idp
  networks:
  - name: shibboleth1
  persistent_disk: 0
  resource_pool: small_z1
  templates:
  - name: idp
    release: shibboleth

networks:
- name: shibboleth1
  subnets:
  - gateway: 10.244.188.1
    name: shibboleth1
    range: 10.244.188.0/24
    static:
    - 10.244.188.2 - 10.244.188.60
  type: manual

properties: {}

releases:
- name: shibboleth
  version: latest

resource_pools:
- cloud_properties:
    name: random
  name: small_z1
  network: shibboleth1
  stemcell:
    name: (( grab meta.stemcell.name ))
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000

