---
jobs:
- name: deploy-shibboleth-staging
  plan:
  - aggregate:
    - get: shibboleth-config
      trigger: true
    - get: common-staging
    - get: pipeline-tasks
    - get: cg-s3-shibboleth-release
    - get: shibboleth-stemcell
      trigger: true
  - task: shibboleth-manifest
    file: shibboleth-config/generate-deployment-manifest.yml
    input_mapping:
      common: common-staging
  - put: shibboleth-staging-deployment
    params:
      cert: common-staging/boshCA.crt
      manifest: shibboleth-manifest/manifest.yml
      releases:
      - cg-s3-shibboleth-release/*.tgz
      stemcells:
      - shibboleth-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy shibboleth on staging
          <$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed shibboleth on staging
          <$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

resources:
- name: common-staging
  type: cg-common
  source:
    region: {{shibboleth-staging-private-region}}
    bucket_name: {{shibboleth-staging-private-bucket}}
    access_key_id: {{ci-access-key-id}}
    secret_access_key: {{ci-secret-access-key}}
    secrets_file: shibboleth-staging.yml
    secrets_passphrase: {{shibboleth-staging-private-passphrase}}
    bosh_cert: bosh.pem

- name: shibboleth-config
  type: git
  source:
    uri: {{cg-deploy-shibboleth-git-url}}
    branch: {{cg-deploy-shibboleth-git-branch}}

- name: shibboleth-stemcell
  type: s3
  source:
    access_key_id: {{ci-access-key-id}}
    bucket: cg-stemcell-images
    regexp: light-bosh-stemcell-(.*)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz
    region_name: us-gov-west-1
    secret_access_key: {{ci-secret-access-key}}

- name: cg-s3-shibboleth-release
  type: s3
  source:
    region_name: {{s3-bosh-releases-region}}
    access_key_id: {{ci-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: shibboleth-(.*).tgz
    secret_access_key: {{ci-secret-access-key}}

- name: shibboleth-staging-deployment
  type: 18f-bosh-deployment
  source:
    target: {{shibboleth-staging-deployment-bosh-target}}
    username: {{shibboleth-staging-deployment-bosh-username}}
    password: {{shibboleth-staging-deployment-bosh-password}}
    deployment: {{shibboleth-staging-deployment-bosh-deployment}}
    ignore_ssl: false

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: 18f-bosh-deployment
  type: docker-image
  source:
    repository: 18fgsa/bosh-deployment-resource
- name: cg-common
  type: docker-image
  source:
    repository: 18fgsa/cg-common-resource
