- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/login/forgotPasswordLink?
  value: https://account.fr.cloud.gov/forgot-password

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/totp/issuerName?
  value: "cloud.gov"

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/entityID?
  value: https://idp.fr.cloud.gov

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/scope?
  value: fr.cloud.gov

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/metadata?/providers?/id=fr?/metadataURL?
  value: https://login.fr.cloud.gov/saml/metadata
