- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/login/forgotPasswordLink?
  value: https://account.fr-stage.cloud.gov/forgot-password

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/totp/issuerName?
  value: "cloud.gov STAGING"

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/entityID?
  value: https://idp.fr-stage.cloud.gov

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/scope?
  value: fr-stage.cloud.gov

- type: replace
  path: /instance_groups/name=idp/jobs/name=idp/properties/idp/metadata?/providers?/id=fr-stage?/metadataURL?
  value: https://login.fr-stage.cloud.gov/saml/metadata
